name: 'Publish'

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DH_USER }}
        password: ${{ secrets.DH_PASS }}
    - name: Publish
      uses: home-assistant/builder@master
      with:
        args: |
          --all \
          --target face_recognition \
          --docker-hub user-name-or-space-name
